name: clone_zoom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^2.2.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.1.18
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.4
  jitsi_meet:
    git:
      url: https://github.com/dispersik/jitsi_meet_fork
      ref: master





  flutter: 
    sdk: flutter
  google_sign_in: ^5.4.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

